name: PublicEconomy
version: 0.1
main: me.lucasemanuel.publiceconomy.Main

commands:
  saldo:
    description: Toggles the saldobox on and off.
    usage: /<command>
    permission: publiceconomy.commands.saldo
  test:
    description: Test
    usage: /<command>
    permission: publiceconomy.commands.test

permissions:
  publiceconomy.commands.saldo:
    default: true
  publiceconomy.commands.test:
    default: op
  publiceconomy.chest.break:
    default: op
  publiceconomy.chest.register:
    default: op